FROM node:13.12.0-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./

RUN npm install node-sass@latest
RUN npm rebuild node-sass
RUN npm install
RUN npm install react-scripts

COPY . ./

CMD ["npm", "start"]
