version: '3'
services: 
    client: 
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes: 
            - ./app/node_modules
            - ./client/:/app
        ports: 
            - 3001:3000
        restart: on-failure
        container_name: client
        tty: true
        environment:
            - CHOKIDAR_USEPOLLING=true
    server:
        build: 
            context: ./server
            dockerfile: Dockerfile.dev
        ports:
            - '3020:3020'
        restart: on-failure
        container_name: server
        tty: true
        volumes: 
            - /app/node_modules
            - ./server/:/app
        environment:
            - NODE_ENV=development
